### ISSUE TITLE
ES5 Target support

### ISSUE THREAD

**Issue by abhijits2000** [tunnelvisionlabs/antlr4ts#423] opened 2019-08-12 17:00 UTC
ANTLR4TS generates Lexer, Parser and Visitor Typescript files are not compatible in ES5 environment. Could you please provide support for ES5 Target for the typescript files?

**Comment by retailify** [comment] 2019-08-12 17:44
duplicate of #311?

**Comment by abhijits2000** [comment] 2019-08-12 17:54
I couldn't see a solution on #311.

**Comment by kevinramharak** [comment] 2019-08-13 08:06
@abhijits2000 How about transpiling the generated files to ES5?

> not sure if this will help, but I was able to work around this issue using Babel to transpile the antlr4ts ES6 to ES5.
> 
> We use Webpack2 and I was able to get it working with a config like this;
> 
> ```
> rules: [
> {
>     test: /\.js$/,
>     exclude: /(node_modules(?!(\/|\\)antlr4ts)|scripts|libs)/,
>     use: {
>         loader: 'babel-loader',
>         options: {
>             presets: ['env']
>         }
>     }
> },
> ```

**Comment by sharwell** [comment] 2020-04-10 19:53
Duplicate of #311

**Closed by sharwell** 2020-04-10 19:53 UTC
