### ISSUE TITLE
TypeError: Class constructor Lexer cannot be invoked without 'new'

### ISSUE THREAD

**Issue by mikecargal** [tunnelvisionlabs/antlr4ts#446] opened 2020-04-10 16:03 UTC
Typescript v3.8.3 

My code:
```typescript
    const inputStream = new ANTLRInputStream("a=5")
    const calcLexer = new CalcLexer(inputStream)
```

I get:
TypeError: Class constructor Lexer cannot be invoked without 'new'
    at new CalcLexer (/Users/mike/zwo-lang/src/main/typescript/gen/CalcLexer.ts:69:3)

Line 69 in CalcLexer.ts (generated code):
```typescript
public static readonly VOCABULARY: Vocabulary = new VocabularyImpl(CalcLexer._LITERAL_NAMES, CalcLexer._SYMBOLIC_NAMES, []);
```

This doesn't appear to be something I can fix from my code.  Has there maybe been TypeScript change that means line 69 was previously valid, but is no longer?

**Comment by BurtHarris** [comment] 2020-04-10 17:48
I think this is caused by a mismatch between the typescript **`target`** setting used to build the antlr4ts run-time library, and the setting used to build your project.   Can you help me confirm?

Update your tsconfig.json to include `    "target": "es2015",` like in https://github.com/tunnelvisionlabs/antlr4ts/blob/master/tsconfig.json#L6

If it works with that change, please note it in this issue, but leave it open.   Thanks.

**Comment by mikecargal** [comment] 2020-04-10 19:21
Indeed, that was the problem... thanks

for some reason I had "es5"

**Comment by sharwell** [comment] 2020-04-10 19:51
Duplicate of #326

**Closed by sharwell** 2020-04-10 19:51 UTC
