### ISSUE TITLE
ANTLR tool code generation for TypeScript

### ISSUE THREAD

**Issue by BurtHarris** [tunnelvisionlabs/antlr4ts#32] opened 2016-10-05 20:34 UTC
To wrap this up, we'll need to provide a new code generator for the tool.   I was thinking that it should probably be usable for JavaScript tools without a TypeScript dependency.   To do this the tool should emit `.js` files, with added `.d.ts` files to enable TypeScript users to benefit from the typings.

This probably belongs in a later milestone.

**Comment by sharwell** [comment] 2016-11-22 16:23
:memo: This was already implemented to generate TypeScript files. The suggestion to generate JavaScript directly is a duplicate of #160.

**Closed by sharwell** 2016-11-22 16:24 UTC
