### ISSUE TITLE
TypeScript version upgrade blocked

### ISSUE THREAD

**Issue by BurtHarris** [tunnelvisionlabs/antlr4ts#460] opened 2020-04-16 01:27 UTC
Strange error behavior if we upgrade to TypeScript version 3.  The tsc command seems to hang or become very slow.

This is related to `import` statements, located outside the runtime's src directory, which use paths including `from "antlr4ts/src/"'...  This causes some sort of recursive compilation behavior.

**Comment by viceice** [comment] 2020-04-16 07:34
duplicate of #459

**Comment by BurtHarris** [comment] 2020-04-16 19:56
closing duplicate

**Closed** 2020-04-16 19:56 UTC
