### ISSUE TITLE
No longer can generate parsers

### ISSUE THREAD

**Issue by mike-lischke** [tunnelvisionlabs/antlr4ts#306] opened 2017-04-01 11:48 UTC
I haven't done this for a while (and it worked before) but with the latest antlr4ts package generating files from grammars fails. The problem is that paths are now handled different than before and I'm not 100% sure this is a problem of antlr4ts and not, maybe, by vscode (where I use this node module).

What happens is this:

1) I have a scripts entry in my package.json for my node module:

```
  "scripts": {
    "antlr4ts": "antlr4ts grammars/ANTLRv4LexBasic.g4 grammars/ANTLRv4Lexer.g4 grammars/ANTLRv4Parser.g4 -o parser/ -visitor"
  },
```

As you can see my 3 grammar files are located in a subfolder called **grammars**.

2) I run the script via npm:

```
npm run-script antlr4ts
```

3) This gives me this output:

```
> antlr4-graps@1.2.17 antlr4ts /Volumes/Extern/Work/projects/antlr4-graps
> antlr4ts grammars/ANTLRv4LexBasic.g4 grammars/ANTLRv4Lexer.g4 grammars/ANTLRv4Parser.g4 -o parser/ -visitor

Generating file '/Volumes/Extern/Work/projects/antlr4-graps/parser/grammars/ANTLRv4LexBasic.ts' for grammar 'grammars/ANTLRv4LexBasic.g4'
Generating file '/Volumes/Extern/Work/projects/antlr4-graps/parser/grammars/ANTLRv4LexBasic.tokens' for grammar 'grammars/ANTLRv4LexBasic.g4'
Generating file '/Volumes/Extern/Work/projects/antlr4-graps/parser/grammars/ANTLRv4Lexer.ts' for grammar 'grammars/ANTLRv4Lexer.g4'
Generating file '/Volumes/Extern/Work/projects/antlr4-graps/parser/grammars/ANTLRv4Lexer.tokens' for grammar 'grammars/ANTLRv4Lexer.g4'
error(160): ANTLRv4Parser.g4:43:18: cannot find tokens file 'parser/ANTLRv4Lexer.tokens'
warning(125): ANTLRv4Parser.g4:47:5: implicit definition of token 'DOC_COMMENT' in parser
warning(125): ANTLRv4Parser.g4:47:41: implicit definition of token 'SEMI' in parser
warning(125): ANTLRv4Parser.g4:51:6: implicit definition of token 'LEXER' in parser
warning(125): ANTLRv4Parser.g4:51:12: implicit definition of token 'GRAMMAR' in parser
warning(125): ANTLRv4Parser.g4:51:22: implicit definition of token 'PARSER' in parser
warning(125): ANTLRv4Parser.g4:68:5: implicit definition of token 'OPTIONS' in parser
warning(125): ANTLRv4Parser.g4:68:13: implicit definition of token 'LBRACE' in parser
...
```

The problem here is that the output is not placed in the **parser** subfolder as specified, but in **parser/grammars**. Well, actually only the output for the first grammar. Further generation fails then because these generated files are not found.

I'm using the latest antlr4ts and antlr4ts-cli node modules.

**Comment by sharwell** [comment] 2017-04-01 12:58
😕 I haven't made any releases any time recently. Were you using a non-Windows system by any chance? If so you were probably hitting #303.

**Comment by mike-lischke** [comment] 2017-04-01 13:01
Yes, that looks related. I'm on macOS and the code generation used to work before. As a workaround I copied the jar to my grammar folder and generated my grammars directly without antlr4ts-cli.

**Comment by mike-lischke** [comment] 2017-04-04 18:03
I just realized that I also need the code generation for getting the ATN for a given grammar, so it's quite essential for me that this gets fixed soon. Sorry for the extra pressure but I'm blocked here currently.

**Comment by sharwell** [comment] 2017-04-07 12:21
Duplicate of #303

**Closed by sharwell** 2017-04-07 12:21 UTC

**Comment by parrt** [comment] 2017-11-04 17:44
@sharwell I added `-Xexact-output-dir` option to fold in a fix to output dir. See https://github.com/antlr/antlr4/pull/2065
